# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import guiche_info_pb2 as guiche__info__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in guiche_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InformationStub(object):
    """Serviço de Informações (Guichê)
    Nome do serviço como esperado pelo cliente
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTerminalOnLine = channel.unary_unary(
                '/guiche_info.Information/GetTerminalOnLine',
                request_serializer=guiche__info__pb2.Empty.SerializeToString,
                response_deserializer=guiche__info__pb2.TerminalAddressResponse.FromString,
                _registered_method=True)


class InformationServicer(object):
    """Serviço de Informações (Guichê)
    Nome do serviço como esperado pelo cliente
    """

    def GetTerminalOnLine(self, request, context):
        """Método para o cliente obter um terminal de atendimento ativo
        Método e request/response atualizados
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InformationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTerminalOnLine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerminalOnLine,
                    request_deserializer=guiche__info__pb2.Empty.FromString,
                    response_serializer=guiche__info__pb2.TerminalAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guiche_info.Information', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guiche_info.Information', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Information(object):
    """Serviço de Informações (Guichê)
    Nome do serviço como esperado pelo cliente
    """

    @staticmethod
    def GetTerminalOnLine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guiche_info.Information/GetTerminalOnLine',
            guiche__info__pb2.Empty.SerializeToString,
            guiche__info__pb2.TerminalAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
