# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guiche_info.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'guiche_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11guiche_info.proto\x12\x0bguiche_info\"\x07\n\x05\x45mpty\"*\n\x17TerminalAddressResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\\\n\x0bInformation\x12M\n\x11GetTerminalOnLine\x12\x12.guiche_info.Empty\x1a$.guiche_info.TerminalAddressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guiche_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_TERMINALADDRESSRESPONSE']._serialized_start=43
  _globals['_TERMINALADDRESSRESPONSE']._serialized_end=85
  _globals['_INFORMATION']._serialized_start=87
  _globals['_INFORMATION']._serialized_end=179
# @@protoc_insertion_point(module_scope)
