# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heartbeat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'heartbeat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\x12\theartbeat\"&\n\x10HeartbeatRequest\x12\x12\n\nservice_id\x18\x01 \x01(\t\"\x0f\n\rEmptyResponse2U\n\tHeartbeat\x12H\n\rSendHeartbeat\x12\x1b.heartbeat.HeartbeatRequest\x1a\x18.heartbeat.EmptyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=30
  _globals['_HEARTBEATREQUEST']._serialized_end=68
  _globals['_EMPTYRESPONSE']._serialized_start=70
  _globals['_EMPTYRESPONSE']._serialized_end=85
  _globals['_HEARTBEAT']._serialized_start=87
  _globals['_HEARTBEAT']._serialized_end=172
# @@protoc_insertion_point(module_scope)
