# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import terminal_pb2 as terminal__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in terminal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TerminalStub(object):
    """Serviço principal do Terminal, chamado pelo Cliente
    Nome do serviço como esperado pelo cliente (TerminalStub)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RentACar = channel.unary_unary(
                '/terminal.Terminal/RentACar',
                request_serializer=terminal__pb2.RentCarRequest.SerializeToString,
                response_deserializer=terminal__pb2.RentCarResponse.FromString,
                _registered_method=True)


class TerminalServicer(object):
    """Serviço principal do Terminal, chamado pelo Cliente
    Nome do serviço como esperado pelo cliente (TerminalStub)
    """

    def RentACar(self, request, context):
        """Cliente requisita a locação de um veículo de uma classe específica
        Método e mensagens atualizados
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RentACar': grpc.unary_unary_rpc_method_handler(
                    servicer.RentACar,
                    request_deserializer=terminal__pb2.RentCarRequest.FromString,
                    response_serializer=terminal__pb2.RentCarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terminal.Terminal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terminal.Terminal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Terminal(object):
    """Serviço principal do Terminal, chamado pelo Cliente
    Nome do serviço como esperado pelo cliente (TerminalStub)
    """

    @staticmethod
    def RentACar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terminal.Terminal/RentACar',
            terminal__pb2.RentCarRequest.SerializeToString,
            terminal__pb2.RentCarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CallbackServiceStub(object):
    """Este é o serviço que o CLIENTE implementa.
    O TERMINAL atuará como CLIENTE deste serviço.
    O cliente do professor define "class CallbackServiceServicer(terminal_pb2_grpc.CallbackServiceServicer):"
    o que significa que esta definição de serviço DEVE estar no terminal.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveCallback = channel.unary_unary(
                '/terminal.CallbackService/ReceiveCallback',
                request_serializer=terminal__pb2.CallbackMessage.SerializeToString,
                response_deserializer=terminal__pb2.CallbackResponse.FromString,
                _registered_method=True)


class CallbackServiceServicer(object):
    """Este é o serviço que o CLIENTE implementa.
    O TERMINAL atuará como CLIENTE deste serviço.
    O cliente do professor define "class CallbackServiceServicer(terminal_pb2_grpc.CallbackServiceServicer):"
    o que significa que esta definição de serviço DEVE estar no terminal.proto
    """

    def ReceiveCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCallback,
                    request_deserializer=terminal__pb2.CallbackMessage.FromString,
                    response_serializer=terminal__pb2.CallbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terminal.CallbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terminal.CallbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallbackService(object):
    """Este é o serviço que o CLIENTE implementa.
    O TERMINAL atuará como CLIENTE deste serviço.
    O cliente do professor define "class CallbackServiceServicer(terminal_pb2_grpc.CallbackServiceServicer):"
    o que significa que esta definição de serviço DEVE estar no terminal.proto
    """

    @staticmethod
    def ReceiveCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terminal.CallbackService/ReceiveCallback',
            terminal__pb2.CallbackMessage.SerializeToString,
            terminal__pb2.CallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
